name = "InteractiveFiction"
uuid = "a1f4fbc3-d079-4fb8-ae0b-772133c9fff8"
authors = ["Avery"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
